DataBase update schema for product
AllaYakymova/Final_Project pull request #9
Opened 2021-01-11 18:04 UTC by uatetiana

2021-01-11 19:23 UTC, Rudenko-alex requested changes
Еще не готов сервак до конца! Чуть позже

2021-01-11 19:23 UTC, Rudenko-alex commented on static/index.html
>  <!DOCTYPE html>
Этот файл для нашего теста был, его не нужно закидывать в репозиторий

2021-01-11 19:23 UTC, Rudenko-alex commented on routes/catalog.js
> -  aupdateCategory
тут проблема, и не поднимался сервак

2021-01-12 22:29 UTC, Rudenko-alex approved these changes

2021-01-12 22:31 UTC, AllaYakymova approved these changes

2021-01-12 22:32 UTC, merged